import { createClient, SupabaseClient } from '@supabase/supabase-js'

let _client: SupabaseClient | null = null

export function getSupabase(): SupabaseClient | null {
  if (_client) return _client
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  if (!url || !key || url.startsWith('your_') || key.startsWith('your_')) return null
  try {
    _client = createClient(url, key)
    return _client
  } catch {
    return null
  }
}

// Convenience export — null in demo mode
export const supabase = null

// ─── MOCK DATA (used when Supabase is not configured) ──────────────────────
export const MOCK_DATA = {
  customers: [
    {
      id: '1',
      created_at: '2024-01-15T10:00:00Z',
      name: 'John & Sarah Mitchell',
      email: 'mitchell@email.com',
      phone: '(720) 555-0101',
      address: '4521 Pine Ridge Dr',
      city: 'Denver',
      state: 'CO',
      zip: '80202',
      notes: 'Large home, 2 AC units, dog on property',
    },
    {
      id: '2',
      created_at: '2024-01-20T10:00:00Z',
      name: 'Westside Property Mgmt',
      email: 'ops@westsideprop.com',
      phone: '(303) 555-0188',
      address: '1200 Commerce St',
      city: 'Denver',
      state: 'CO',
      zip: '80204',
      notes: 'Commercial client - 8 units, monthly maintenance contract',
    },
    {
      id: '3',
      created_at: '2024-02-01T10:00:00Z',
      name: 'Carlos Rivera',
      email: 'crivera@gmail.com',
      phone: '(720) 555-0234',
      address: '890 Maple Ave',
      city: 'Aurora',
      state: 'CO',
      zip: '80010',
      notes: '',
    },
    {
      id: '4',
      created_at: '2024-02-10T10:00:00Z',
      name: 'Denver Office Plaza',
      email: 'facilities@denverplaza.com',
      phone: '(303) 555-0312',
      address: '5500 S Quebec St',
      city: 'Greenwood Village',
      state: 'CO',
      zip: '80111',
      notes: 'After hours access requires security badge. Contact Frank at ext 201.',
    },
    {
      id: '5',
      created_at: '2024-02-15T10:00:00Z',
      name: 'Amy Thornton',
      email: 'athornton@yahoo.com',
      phone: '(720) 555-0456',
      address: '234 Oak Street',
      city: 'Lakewood',
      state: 'CO',
      zip: '80226',
      notes: 'Elderly homeowner, mornings only',
    },
  ],
  jobs: [
    {
      id: '1',
      created_at: '2024-02-20T09:00:00Z',
      job_number: 'JOB-001',
      customer_id: '1',
      technician_id: '1',
      title: 'AC Tune-Up & Filter Replacement',
      description: 'Annual maintenance on 2 units',
      status: 'scheduled' as const,
      priority: 'medium' as const,
      scheduled_date: new Date().toISOString().split('T')[0],
      scheduled_time: '09:00',
      estimated_duration: 90,
      address: '4521 Pine Ridge Dr',
      city: 'Denver',
      state: 'CO',
      zip: '80202',
      notes: 'Dog on property. Park in driveway.',
    },
    {
      id: '2',
      created_at: '2024-02-20T09:00:00Z',
      job_number: 'JOB-002',
      customer_id: '3',
      technician_id: '2',
      title: 'Emergency Furnace Repair',
      description: 'Furnace not heating - emergency call',
      status: 'in_progress' as const,
      priority: 'emergency' as const,
      scheduled_date: new Date().toISOString().split('T')[0],
      scheduled_time: '10:30',
      estimated_duration: 120,
      address: '890 Maple Ave',
      city: 'Aurora',
      state: 'CO',
      zip: '80010',
      notes: '',
    },
    {
      id: '3',
      created_at: '2024-02-19T09:00:00Z',
      job_number: 'JOB-003',
      customer_id: '2',
      technician_id: '1',
      title: 'Commercial HVAC Inspection',
      description: 'Monthly inspection - 8 units',
      status: 'completed' as const,
      priority: 'low' as const,
      scheduled_date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      scheduled_time: '08:00',
      estimated_duration: 180,
      address: '1200 Commerce St',
      city: 'Denver',
      state: 'CO',
      zip: '80204',
      notes: 'Check filters on roof units.',
      completed_at: new Date(Date.now() - 80000000).toISOString(),
    },
    {
      id: '4',
      created_at: '2024-02-20T09:00:00Z',
      job_number: 'JOB-004',
      customer_id: '5',
      title: 'New AC Installation',
      description: 'Install new 3-ton Carrier unit',
      status: 'pending' as const,
      priority: 'medium' as const,
      scheduled_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
      scheduled_time: '09:00',
      estimated_duration: 240,
      address: '234 Oak Street',
      city: 'Lakewood',
      state: 'CO',
      zip: '80226',
      notes: 'Customer requests morning appointment only.',
    },
    {
      id: '5',
      created_at: '2024-02-20T09:00:00Z',
      job_number: 'JOB-005',
      customer_id: '4',
      technician_id: '2',
      title: 'HVAC System Inspection',
      description: 'Quarterly inspection of all HVAC systems',
      status: 'scheduled' as const,
      priority: 'low' as const,
      scheduled_date: new Date(Date.now() + 172800000).toISOString().split('T')[0],
      scheduled_time: '14:00',
      estimated_duration: 120,
      address: '5500 S Quebec St',
      city: 'Greenwood Village',
      state: 'CO',
      zip: '80111',
      notes: 'Security badge required. Contact Frank at ext 201.',
    },
  ],
  technicians: [
    {
      id: '1',
      created_at: '2024-01-01T00:00:00Z',
      name: 'Hunter Martinez',
      email: 'hunter@mountainclimate.com',
      phone: '(720) 555-0001',
      color: '#3B82F6',
      active: true,
    },
    {
      id: '2',
      created_at: '2024-01-01T00:00:00Z',
      name: 'Jake Torres',
      email: 'jake@mountainclimate.com',
      phone: '(720) 555-0002',
      color: '#10B981',
      active: true,
    },
  ],
  invoices: [
    {
      id: '1',
      created_at: '2024-02-19T16:00:00Z',
      invoice_number: 'INV-001',
      job_id: '3',
      customer_id: '2',
      status: 'sent' as const,
      line_items: [
        { id: '1', description: 'Monthly HVAC Inspection (8 units)', quantity: 1, unit_price: 450, total: 450 },
        { id: '2', description: 'Filter Replacements (16 filters)', quantity: 16, unit_price: 12, total: 192 },
      ],
      subtotal: 642,
      tax_rate: 0.08,
      tax_amount: 51.36,
      total: 693.36,
      due_date: new Date(Date.now() + 2592000000).toISOString().split('T')[0],
    },
    {
      id: '2',
      created_at: '2024-02-15T14:00:00Z',
      invoice_number: 'INV-002',
      customer_id: '1',
      status: 'paid' as const,
      line_items: [
        { id: '1', description: 'AC System Diagnostic', quantity: 1, unit_price: 95, total: 95 },
        { id: '2', description: 'Refrigerant Recharge (2 lbs)', quantity: 2, unit_price: 75, total: 150 },
        { id: '3', description: 'Labor (2 hrs)', quantity: 2, unit_price: 110, total: 220 },
      ],
      subtotal: 465,
      tax_rate: 0.08,
      tax_amount: 37.20,
      total: 502.20,
      due_date: new Date(Date.now() - 1296000000).toISOString().split('T')[0],
      paid_at: new Date(Date.now() - 864000000).toISOString(),
    },
    {
      id: '3',
      created_at: '2024-02-10T09:00:00Z',
      invoice_number: 'INV-003',
      customer_id: '3',
      status: 'overdue' as const,
      line_items: [
        { id: '1', description: 'Emergency Service Call', quantity: 1, unit_price: 150, total: 150 },
        { id: '2', description: 'Ignitor Replacement', quantity: 1, unit_price: 85, total: 85 },
        { id: '3', description: 'Labor (1.5 hrs)', quantity: 1.5, unit_price: 110, total: 165 },
      ],
      subtotal: 400,
      tax_rate: 0.08,
      tax_amount: 32,
      total: 432,
      due_date: new Date(Date.now() - 1296000000).toISOString().split('T')[0],
    },
  ],
}
